version: "3"
services:
  app:
    image: index_rework_front
    container_name: index_rework_front
    stdin_open: true
    tty: True
    restart: always
    ports:
      - "5913:3000"
    volumes:
      - ./:/app